name: dart_domainrobot_sdk
description: A dart package for easy integration of the domainrobot API powered by InterNetX GmbH.
version: 0.5.1
author: InterNetX GmbH <entwicklung@internetx.com>
homepage: https://github.com/InterNetX/dart-domainrobot-sdk
publish_to: https://pub.dartlang.org

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  basic_utils: ^2.4.7
  logging: ^0.11.3+2
  http: ^0.12.0+2
  json_annotation: ">=2.0.0 <=3.0.1"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
  build_runner: ^1.6.0
  json_serializable: ^3.2.2